-keep class com.lyracore.zoho.chat.models.** { *; }
-keep interface com.lyracore.zoho.chat.interfaces.** { *; }
-keep class com.lyracore.zoho.core.models.** { *; }
-keep interface com.lyracore.zoho.core.interfaces.** { *; }
-keep class com.lyracore.zoho.department.models.** { *; }